In [6]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
iris = load_iris()

In [4]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
X = iris.data
y = (iris.target == 0).astype(int)

numpy array에서 쉽게 필터하는법!  
setosa인 데이터를 0 -> 1로 바꿔야하는데  
(iris.target == 0) Trusly한 값으로 보고 int로 변환하면 1로 변환되고, 아닌 경우는 0으로 변환됨  

In [6]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [12]:
y_test

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1])

In [13]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1])

In [28]:
y_proba = model.predict_proba(X_test) # [0을 예측할 확률] / [1을 예측할 확률]

In [26]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [23]:
confusion_matrix(y_test, y_pred)

array([[20,  0],
       [ 0, 10]])

30개 데이터 중에  
               예측: Positive 예측: Negative  
실제: Positive  True Positive (TP)20 / False Negative (FN)0  
실제: Negative  False Positive (FP)0	/ True Negative (TN)10  

In [25]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Accuracy:  {accuracy:.3f}")
print(f"Precision: {precision:.3f}")
print(f"Recall:    {recall:.3f}")
print(f"F1-Score:  {f1:.3f}")

Accuracy:  1.000
Precision: 1.000
Recall:    1.000
F1-Score:  1.000


In [27]:
from sklearn.metrics import roc_auc_score, roc_curve

In [33]:
y_proba[:,1]

array([4.55385779e-03, 9.58520512e-01, 5.40034424e-06, 6.13513643e-03,
       2.25748581e-03, 9.63198614e-01, 6.06507656e-02, 6.37960994e-04,
       3.03502235e-03, 2.72273531e-02, 1.08841436e-03, 9.74974390e-01,
       9.80864653e-01, 9.70317035e-01, 9.78952648e-01, 4.51726428e-03,
       1.61150629e-04, 2.72165121e-02, 7.65407072e-03, 2.19300520e-04,
       9.66047949e-01, 2.02072539e-03, 9.61368929e-01, 2.40334577e-04,
       5.73021354e-05, 5.09630724e-04, 1.36923149e-04, 1.23785768e-04,
       9.70092769e-01, 9.61459028e-01])

In [36]:
# ROC Curve 계산
FPR, TPR, threshold = roc_curve(y_test, y_proba[:,1])

In [37]:
# AUC 계산
roc_auc_score(y_test, y_proba[:,1])

1.0

---
### 당뇨병 실습: Outcome 예측

In [38]:
import pandas as pd
df = pd.read_csv('train.csv')

In [39]:
df

ID  Pregnancies  Glucose  ...  DiabetesPedigreeFunction  Age  Outcome
0    TRAIN_000            4      103  ...                     0.966   33        0
1    TRAIN_001           10      133  ...                     0.245   36        0
2    TRAIN_002            4      112  ...                     0.236   38        0
3    TRAIN_003            1      119  ...                     0.507   26        0
4    TRAIN_004            1      114  ...                     0.289   21        0
..         ...          ...      ...  ...                       ...  ...      ...
647  TRAIN_647            1       91  ...                     0.192   21        0
648  TRAIN_648           10      122  ...                     0.258   41        0
649  TRAIN_649            8       84  ...                     0.457   39        0
650  TRAIN_650            2       81  ...                     0.547   25        0
651  TRAIN_651            1      107  ...                     0.165   24        0

[652 rows x 10 columns]

In [42]:
df_t = df.drop(['Outcome', 'Pregnancies'], axis=1).replace(0, None)
df_t[['Outcome', 'Pregnancies']] = df[['Outcome', 'Pregnancies']]
df_t = df_t.dropna()
df_t

ID Glucose BloodPressure  ... Age Outcome Pregnancies
0    TRAIN_000     103            60  ...  33       0           4
3    TRAIN_003     119            88  ...  26       0           1
4    TRAIN_004     114            66  ...  21       0           1
5    TRAIN_005      78            50  ...  26       1           3
6    TRAIN_006      91            54  ...  23       0           1
..         ...     ...           ...  ...  ..     ...         ...
636  TRAIN_636     171           110  ...  54       1           9
637  TRAIN_637     152            90  ...  43       1          13
638  TRAIN_638     139            62  ...  21       0           1
643  TRAIN_643     147            74  ...  30       0           4
650  TRAIN_650      81            72  ...  25       0           2

[332 rows x 10 columns]

In [47]:
X = df_t.drop(['ID', 'Outcome'], axis=1)
y = df_t['Outcome']

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [50]:
model = LogisticRegression()
model.fit(X_train, y_train)

/opt/anaconda3/envs/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [51]:
y_pred = model.predict(X_test)

In [52]:
y_proba = model.predict_proba(X_test)

In [53]:
y_proba

array([[0.80540161, 0.19459839],
       [0.90371382, 0.09628618],
       [0.83754421, 0.16245579],
       [0.96403869, 0.03596131],
       [0.91964711, 0.08035289],
       [0.86441398, 0.13558602],
       [0.25585659, 0.74414341],
       [0.37624406, 0.62375594],
       [0.67914981, 0.32085019],
       [0.24266155, 0.75733845],
       [0.21726339, 0.78273661],
       [0.54449928, 0.45550072],
       [0.90469726, 0.09530274],
       [0.96690933, 0.03309067],
       [0.74448421, 0.25551579],
       [0.90065319, 0.09934681],
       [0.9880306 , 0.0119694 ],
       [0.89873245, 0.10126755],
       [0.34137729, 0.65862271],
       [0.77788134, 0.22211866],
       [0.92404288, 0.07595712],
       [0.77392141, 0.22607859],
       [0.95679165, 0.04320835],
       [0.31754263, 0.68245737],
       [0.63952394, 0.36047606],
       [0.87818182, 0.12181818],
       [0.904179  , 0.095821  ],
       [0.95118347, 0.04881653],
       [0.57233116, 0.42766884],
       [0.9190917 , 0.0809083 ],
       [0.

In [56]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred, target_names=['Normal', 'Diabetes']))

              precision    recall  f1-score   support

      Normal       0.76      0.93      0.84        45
    Diabetes       0.75      0.41      0.53        22

    accuracy                           0.76        67
   macro avg       0.76      0.67      0.68        67
weighted avg       0.76      0.76      0.74        67



In [57]:
roc_auc_score(y_test, y_proba[:,1])

0.8282828282828283