# NumPy 마스터하기: 데이터 분석의 첫걸음 (Colab 실습 교안)

이 노트북은 Python 데이터 분석의 핵심 라이브러리인 NumPy의 주요 기능들을 실습하는 것을 목표로 합니다. 아래의 코드 셀들을 순서대로 실행하며 NumPy와 친숙해져 보세요.

#### **0. NumPy 라이브러리 불러오기**
NumPy를 사용하기 전에는 반드시 라이브러리를 `import` 해야 합니다. 관례적으로 `np`라는 별칭을 붙여 사용합니다.

In [1]:
import numpy as np

---
### **1. NumPy 배열 생성하기**

#### **📜 개념 설명**
NumPy의 핵심은 `ndarray`(N차원 배열) 객체입니다. 이 자료구조는 숫자 데이터를 다루는 데 최적화되어 있으며, Python 리스트보다 훨씬 빠르고 수학적 연산에 유용한 기능이 많습니다. Python 리스트를 이용해 간단하게 만들 수 있습니다.

#### **🛠️ 사용 방법**
`np.array()` 함수에 Python 리스트를 전달합니다. 2차원 배열(행렬)을 만들려면 리스트 안에 리스트를 넣는 중첩 구조를 사용합니다.

In [ ]:
# 1차원 배열 생성
list_1d = [1, 2, 3, 4, 5]
arr1d = np.array(list_1d)
print("1차원 배열:\n", arr1d)

# 2차원 배열(행렬) 생성
list_2d = [[10, 20, 30], [40, 50, 60]]
arr2d = np.array(list_2d)
print("\n2차원 배열:\n", arr2d)

#### **✍️ 실습 문제**
3명의 환자 데이터를 담은 2차원 NumPy 배열 `patient_data`를 만들어 보세요. 각 환자의 데이터는 `[키(cm), 체중(kg), 나이(세)]` 순서입니다.
* **환자 1**: `[175, 72, 45]`
* **환자 2**: `[160, 58, 32]`
* **환자 3**: `[182, 85, 51]`

In [2]:
patient_data = np.array([
    [175, 72, 45],
    [160, 58, 32],
    [182, 85, 51]
])

In [3]:
print(patient_data)

[[175  72  45]
 [160  58  32]
 [182  85  51]]


---
### **2. 배열의 속성 확인**

#### **📜 개념 설명**
데이터의 구조를 파악하는 것은 매우 중요합니다. NumPy 배열은 `shape`(형태), `ndim`(차원), `dtype`(데이터 타입)과 같은 메타데이터를 속성으로 가지고 있습니다.

#### **🛠️ 사용 방법**
NumPy 배열 변수 뒤에 점(`.`)을 찍어 해당 속성에 접근할 수 있습니다.
* `배열.shape`: 각 차원의 크기를 튜플로 반환합니다. (행, 열)
* `배열.ndim`: 차원의 개수를 반환합니다.
* `배열.dtype`: 배열에 저장된 원소의 데이터 타입을 반환합니다.

In [ ]:
# 이전 섹션에서 만든 patient_data 배열을 사용합니다.
print("배열의 형태 (shape):", patient_data.shape)
print("배열의 차원 (ndim):", patient_data.ndim)
print("배열의 데이터 타입 (dtype):", patient_data.dtype)

#### **✍️ 실습 문제**
4명의 학생에 대한 2과목의 시험 점수 데이터 `[[88, 92], [75, 81], [95, 99], [61, 72]]`를 담은 `score_data` 배열을 만들고, 그 배열의 **형태**와 **차원 수**를 출력해 보세요.

In [47]:
score_data = np.array([
    [88, 92],
    [75, 81],
    [95, 99],
    [61, 72]
])

print(score_data.shape)
print(score_data.ndim)

(4, 2)
2


---
### **3. 인덱싱과 슬라이싱 (데이터 추출)**

#### **📜 개념 설명**
인덱싱과 슬라이싱은 배열에서 특정 원소나 부분 집합을 추출하는 기술입니다. 분석에 필요한 데이터만 골라내는 데 필수적입니다.

#### **🛠️ 사용 방법**
대괄호 `[]`를 사용해 데이터에 접근합니다. 2차원 배열은 `배열[행, 열]` 형식입니다. 콜론(`:`)은 특정 축의 모든 원소 또는 범위를 선택하는 슬라이싱에 사용됩니다.
* `배열[2]`: 3번째 행 전체에 접근합니다. (인덱스는 0부터 시작)
* `배열[2, 1]`: 3번째 행, 2번째 열의 원소 하나에 접근합니다.
* `배열[:, 1]`: 모든 행(`:`)의 2번째 열 데이터만 추출합니다.
* `배열[0:2, :]`: 1번째 행부터 2번째 행까지(`0:2`는 인덱스 0, 1을 의미), 그리고 모든 열(`:`)을 추출합니다.

In [ ]:
# patient_data 배열에서 데이터 추출하기
# 첫 번째 환자 정보 (인덱스 0번 행)
print("1번 환자 정보:", patient_data[0])

# 세 번째 환자의 나이 (인덱스 2번 행, 2번 열)
print("3번 환자 나이:", patient_data[2, 2])

# 모든 환자의 체중 (모든 행, 인덱스 1번 열)
print("모든 환자 체중:", patient_data[:, 1])

#### **✍️ 실습 문제**
`patient_data` 배열을 이용하여 다음 정보를 추출해 보세요.
1.  **두 번째 환자**(인덱스 1)의 **체중**(인덱스 1)
2.  **모든 환자**의 **나이**(인덱스 2)
3.  **세 번째 환자**(인덱스 2)의 **모든 정보**

In [16]:
print(patient_data[1][1])
print(patient_data[:, 2])
print(patient_data[2])

58
[45 32 51]
[182  85  51]


---
### **4. 벡터화 연산 (Vectorized Operation)**

#### **📜 개념 설명**
벡터화는 NumPy의 가장 강력한 기능입니다. `for` 반복문 없이 배열 전체에 대해 산술 연산을 한 번에 적용할 수 있게 해줍니다. 코드가 매우 간결해지고 연산 속도가 비약적으로 빨라집니다.

#### **Part 1: 스칼라-벡터 연산 (배열과 숫자 간의 연산)**

##### **🛠️ 사용 방법**
NumPy 배열과 숫자(스칼라) 사이에 일반적인 산술 연산자(`+`, `-`, `*`, `/`)를 사용하면 됩니다. 연산은 배열의 모든 원소에 자동으로 적용(브로드캐스팅)됩니다.

In [ ]:
arr = np.array([1, 2, 3])
print("배열에 10 더하기:", arr + 10)
print("배열에 2 곱하기:", arr * 2)

##### **✍️ 실습 문제**
`patient_data` 배열에서 모든 환자의 **키(cm)를 미터(m) 단위로 변환**하세요.
1.  먼저 모든 환자의 키 데이터(인덱스 0번 열)를 추출합니다.
2.  추출된 배열을 100으로 나눕니다.

In [26]:
patient_height_m = patient_data[:, 0] / 100
print(patient_height_m)

[1.75 1.6  1.82]


#### **Part 2: 벡터-벡터 연산 (배열과 배열 간의 연산)**
**같은 크기**를 가진 두 배열 사이의 연산은 같은 위치에 있는 원소끼리(element-wise) 수행됩니다.

##### **🛠️ 사용 방법**
크기가 동일한 두 NumPy 배열 사이에 산술 연산자를 사용하면, 같은 위치의 원소끼리 연산이 이루어집니다.

In [ ]:
midterm_scores = np.array([80, 75, 90])
final_scores = np.array([85, 95, 88])

# 같은 인덱스의 원소끼리 더함: 80+85, 75+95, 90+88
total_scores = midterm_scores + final_scores
print("합산 총점:", total_scores)

##### **✍️ 실습 문제**
환자 3명의 체중(kg)을 담은 `weights_kg` 배열과 키(m)를 담은 `heights_m` 배열이 주어졌을 때, 각 환자의 **BMI(체질량지수)를 계산**해 보세요.
* **BMI 계산 공식**: `체중(kg) / (키(m) ** 2)`

In [28]:
# 주어진 데이터
weights_kg = np.array([72, 58, 85])
heights_m = np.array([1.75, 1.60, 1.82])

In [30]:
bmi = weights_kg / heights_m **2
print(bmi)

[23.51020408 22.65625    25.66115203]


---
### **5. 조건 필터링 (Boolean Indexing)**

#### **📜 개념 설명**
조건 필터링은 특정 조건을 만족하는 데이터만 `True`로 표시하여 골라내는 매우 유용한 기능입니다. 데이터의 부분집합을 추출하여 분석을 심화할 수 있습니다.

#### **🛠️ 사용 방법**
1.  배열에 조건식(예: `배열 > 30`)을 적용하여 `True`와 `False`로 이루어진 **불리언 마스크(boolean mask)** 배열을 만듭니다.
2.  생성된 마스크를 원본 배열의 인덱스 자리에 넣으면, 마스크 값이 `True`인 위치의 원소만 추출됩니다.

In [ ]:
age_arr = np.array([10, 45, 22, 58, 31])

# 1단계: 불리언 마스크 생성
age_mask = age_arr > 30
print("30보다 큰가? (마스크):", age_mask)

# 2단계: 마스크를 이용해 데이터 필터링
print("30보다 큰 값:", age_arr[age_mask])

#### **✍️ 실습 문제**
`patient_data` 배열에서 **나이가 50세 이상인 환자**의 **모든 데이터(키, 체중, 나이)**를 추출해 보세요.

In [33]:
age_mask = patient_data[:, 2] > 50
print(patient_data[age_mask])

[[182  85  51]]


---
### **6. 기본 통계 계산**

#### **📜 개념 설명**
NumPy는 데이터의 통계적 특성을 파악하는 데 유용한 함수들을 제공합니다. 이를 통해 데이터를 요약하고 이해할 수 있습니다.
* **평균** (`np.mean()`): 모든 원소의 평균값
* **최댓값** (`np.max()`): 가장 큰 값
* **최솟값** (`np.min()`): 가장 작은 값
* **합계** (`np.sum()`): 모든 원소의 합
* **표준편차** (`np.std()`): 데이터가 평균으로부터 얼마나 퍼져있는지를 나타내는 값

#### **🛠️ 사용 방법**
통계 함수는 배열 전체에 적용하거나, `axis` 매개변수를 사용하여 특정 축(방향)을 기준으로 적용할 수 있습니다.
* `axis=0`: **열(세로)** 방향으로 연산을 수행합니다.
* `axis=1`: **행(가로)** 방향으로 연산을 수행합니다.

In [ ]:
# patient_data 배열 사용
# 배열 전체 원소의 평균
print("전체 평균:", np.mean(patient_data))

# 각 열(특성)의 평균 계산 (axis=0) -> [평균 키, 평균 체중, 평균 나이]
column_means = np.mean(patient_data, axis=0)
print("열(특성)별 평균:", column_means)

# 각 행(환자)의 최댓값 계산 (axis=1)
row_maxes = np.max(patient_data, axis=1)
print("행(환자)별 최댓값:", row_maxes)

#### **✍️ 실습 문제**
`patient_data` 배열을 사용하여 다음 통계치를 계산하고 출력해 보세요.
1.  모든 환자의 **평균 나이**
2.  가장 **무거운 체중(최댓값)**

In [36]:
print(np.mean(patient_data[:,2]))
print(np.max(patient_data[:,1]))

42.666666666666664
85


---
### **7. 종합 실습 🏋️**
지금까지 배운 내용을 종합하여 직접 데이터를 만들어 다루어 봅시다.

#### **✍️ 실습 문제**
1.  **나의 건강 벡터 만들기**: `[나의 주간 평균 운동 시간(분), 평균 수면 시간, 키(cm)]`를 변수 `my_vector`에 NumPy 배열로 저장해 보세요.
2.  **팀 정보 행렬 만들기**: 주변 친구나 동료 2명의 (가상) 데이터를 추가하여, 당신의 벡터와 합쳐 3x3 크기의 `team_matrix`를 만들어 보세요.
3.  **특정 정보 꺼내보기**: `team_matrix`에서 다음을 추출하여 출력하세요.
    * 두 번째 사람의 모든 정보
    * 세 사람 모두의 키 정보

In [37]:
my_vector = np.array([120, 8, 160])

In [41]:
team_matrix = np.array([
    my_vector,
    [180, 7, 163],
    [170, 6, 155],
])

In [46]:
print(team_matrix[1])
print(team_matrix[:,2])

[180   7 163]
[160 163 155]
